### ISSUE TITLE
A Better Optimized Way to do Logging!

### ISSUE THREAD

**Issue by lnxpy** [sys113/negar#3]
Hey @sys113 :smiley:,

You could also use decorators in the component scripts.
It really increases the flexibility and readability of your code instead of being lingered.

cmpt.py
```python
def log_this(func):
    file = open('log.txt', 'a')
    file.write('[~%s~] - %s' % (func()['log_type'],
                              func()['log_text']))
    file.write('\n')
    file.close()
...
```

main.py
```python
from cmpt import log_this

@log_this
def main():
    return {
        'log_type': 'error',
        'log_text': 'This is the log text',
    }
...
```
It'll create something like this..
```
[~error~] - This is the log text
...
```
Though you can change the style just like negar.

It's such a simple example to start optimizing :).
Read more about decorators [here](https://www.python-course.eu/python3_decorators.php).
And also you can use your decorators in your self-made class as you can see [here](https://stackoverflow.com/questions/1263451/python-decorators-in-classes).

Take care,
Thanks :heart:

**Comment by hamid-shahsavani** [comment]
hello lnxpy , Thanks for your suggestion! ;D
